# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplebd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='busy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
