# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplebd', '0003_auto_20160731_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
