# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplebd', '0006_auto_20160801_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Руки из жопы'), (1, 'Нет отпыта'), (2, 'Норма'), (3, 'Хорош'), (4, 'Мастер от Б-га')], default=2),
        ),
    ]
