# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peoplebd', '0007_auto_20160801_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='busy_days',
            field=models.ManyToManyField(blank=True, related_name='who_busy', to='peoplebd.Days'),
        ),
    ]
