# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peoplebd', '0009_remove_person_busy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
